"""
Django settings for django-celery-jobs project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv('.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y@z3$=_uj-^xk5mb8q+#hqbq1%)120s2cye_g0)rio=#c2=cas'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework_simplejwt',
    'django_extensions',

    'django_celery_results',
    'django_celery_beat',
    'django_celery_jobs',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'celery_jobs_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [str(BASE_DIR / 'templates')],  # HTML 文件存储位置
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'celery_jobs_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("MYSQL:LOCAL:DB_NAME"),
        'HOST': os.getenv("MYSQL:LOCAL:HOST"),
        'PORT': os.getenv("MYSQL:LOCAL:PORT"),
        'USER': os.getenv("MYSQL:LOCAL:USER"),
        'PASSWORD': os.getenv("MYSQL:LOCAL:PASSWORD"),
        'OPTIONS': {'charset': 'utf8mb4'},
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache => Django4.x
CACHES = {
    'default': {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",

        # schema format: redis://username:password@host:port (redis default port: 6379)
        # No Authentication:                redis://127.0.0.1:6379
        # Password-only Authentication:     redis://:password@127.0.0.1:6379
        # Username-Password Authentication: redis://username:password@127.0.0.1:6379
        "LOCATION": "redis://{user}:{pwd}@{host}:{port}".format(
            user=os.getenv('REDIS:USER'), pwd=os.getenv('REDIS:PASSWORD'),
            host=os.getenv('REDIS:HOST'), port=os.getenv('REDIS:PORT'),
        ),
        "OPTIONS": {
            # 数据库0，redis默认附带16个逻辑数据库(0-15)
            'db': os.getenv('REDIS:DB0'),

            # 解析类，可以不指定，如果显式指定，就必须安装hiredis
            "parser_class": "redis.connection.HiredisParser",

            # 连接池类
            'pool_class': 'redis.ConnectionPool'
        }
    },
}

# django-cors-headers
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = []
CORS_ALLOW_METHODS = ["DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT",]
CORS_ALLOW_HEADERS = ["*"]

# DjangoRestFramework-SimpleJwt
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/getting_started.html
# https://github.com/jazzband/djangorestframework-simplejwt
# pip install djangorestframework-simplejwt[crypto]
days = 7 if DEBUG else 1
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=days),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=days),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_code',
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('XX-Token',),
}

# DjangoRestFramework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}


# Set Celery App Path
# CELERY_APP = 'celery_jobs_demo.celery:celery_app'
CELERY_APP = 'celery_jobs_demo.t_celery:app'

# Celery Beat Start Raise:
#     ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False
DJANGO_CELERY_BEAT_TZ_AWARE = False
