# Generated by Django 4.1.7 on 2023-05-13 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryNativeTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, default='', max_length=500, verbose_name='Name')),
                ('task', models.CharField(blank=True, default='', max_length=500, unique=True, verbose_name='Task')),
                ('backend', models.CharField(blank=True, default='', max_length=500, verbose_name='Backend')),
                ('priority', models.IntegerField(blank=True, default=None, null=True, verbose_name='Priority')),
                ('ignore_result', models.BooleanField(blank=True, default=False, verbose_name='Ignore Result')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hidden')),
                ('desc', models.CharField(blank=True, default='', max_length=500, verbose_name='Desc')),
            ],
            options={
                'db_table': 'django_celery_jobs_native_jobs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeployOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('mode', models.SmallIntegerField(blank=True, choices=[(1, 'worker'), (2, 'beat'), (3, 'celeryd'), (4, 'multi'), (5, 'init-script'), (6, 'systemd'), (7, 'supervisor')], default=1, verbose_name='Deploy Mode')),
                ('name', models.CharField(blank=True, default='', max_length=30, verbose_name='Name')),
                ('alias', models.CharField(blank=True, default='', max_length=100, verbose_name='Alias')),
                ('value', models.CharField(blank=True, default='', max_length=5000, verbose_name='Value')),
                ('order', models.IntegerField(blank=True, default=1, verbose_name='Order')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Description')),
            ],
            options={
                'db_table': 'django_celery_jobs_deploy_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('transport', models.CharField(blank=True, default='', max_length=50, verbose_name='Transport')),
                ('user', models.CharField(blank=True, default='', max_length=50, verbose_name='User')),
                ('pwd', models.CharField(blank=True, default='', max_length=200, verbose_name='Password')),
                ('host', models.CharField(blank=True, default='', max_length=50, verbose_name='Host')),
                ('port', models.IntegerField(blank=True, default=0, verbose_name='Port')),
                ('virtual', models.CharField(blank=True, default='', max_length=50, verbose_name='Broker Virtual Host')),
                ('category', models.SmallIntegerField(blank=True, choices=[(1, 'broker'), (2, 'ssh'), (3, 'http')], default=0, verbose_name='Config Category')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_celery_jobs_config',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JobRunnerResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('task_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Job ID')),
                ('task_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Job Name')),
                ('periodic_task_id', models.IntegerField(blank=True, default=0, verbose_name='Periodic Task Id')),
                ('status', models.CharField(blank=True, choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50, verbose_name='Job Status')),
                ('cost_seconds', models.IntegerField(blank=True, default=0, verbose_name='Cost Seconds')),
                ('args', models.JSONField(blank=True, default=list, verbose_name='Positional Arguments')),
                ('kwargs', models.JSONField(blank=True, default=dict, verbose_name='Keyword Arguments')),
                ('result', models.CharField(blank=True, default='', max_length=2000, verbose_name='Job Result')),
                ('run_date', models.DateTimeField(blank=True, default='1979-01-01 00:00:00', verbose_name='Run Datetime')),
                ('traceback', models.CharField(blank=True, default='', max_length=3000, verbose_name='Traceback')),
                ('done_date', models.DateTimeField(blank=True, default='1979-01-01 00:00:00', verbose_name='Done Datetime')),
                ('system', models.CharField(blank=True, default='', max_length=100, verbose_name='System')),
                ('ip_address', models.CharField(blank=True, default='', max_length=20, verbose_name='Ip')),
                ('node', models.CharField(blank=True, default='', max_length=100, verbose_name='Node')),
                ('remark', models.CharField(blank=True, default='', max_length=300, verbose_name='remark')),
            ],
            options={
                'db_table': 'django_celery_jobs_runner_result',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JobScheduledResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sched_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Scheduled Id')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='Scheduled Name')),
                ('periodic_task_id', models.IntegerField(blank=True, default=0, verbose_name='Periodic Task Id')),
                ('run_date', models.DateTimeField(blank=True, default='1979-01-01 00:00:00', verbose_name='Run Datetime')),
                ('is_success', models.BooleanField(blank=True, default=False, verbose_name='Is Success')),
                ('system', models.CharField(blank=True, default='', max_length=100, verbose_name='System')),
                ('ip_address', models.CharField(blank=True, default='', max_length=20, verbose_name='Ip')),
                ('node', models.CharField(blank=True, default='', max_length=100, verbose_name='Node')),
                ('traceback', models.CharField(blank=True, default='', max_length=3000, verbose_name='Traceback')),
                ('remark', models.CharField(blank=True, default='', max_length=300, verbose_name='Remark')),
            ],
            options={
                'db_table': 'django_celery_jobs_scheduled_result',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BeatPeriodicTaskModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.CreateModel(
            name='CeleryTaskRunnerResultModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_results.taskresult',),
        ),
        migrations.CreateModel(
            name='JobPeriodicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='Task Title')),
                ('is_enabled', models.BooleanField(blank=True, default=False, verbose_name='Start or not')),
                ('max_run_cnt', models.IntegerField(blank=True, default=0, verbose_name='Maximum execution times')),
                ('first_run_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='First run datetime')),
                ('deadline_run_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deadline run datetime')),
                ('func_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Func Name')),
                ('task_source_code', models.TextField(blank=True, default='', verbose_name='Task Source Code')),
                ('remark', models.CharField(default='', max_length=1000, verbose_name='remark')),
                ('config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config', to='django_celery_jobs.jobconfigmodel')),
                ('periodic_task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_task', to='django_celery_beat.periodictask')),
            ],
            options={
                'db_table': 'django_celery_jobs_periodic_task',
                'ordering': ['-id'],
            },
        ),
    ]
