# Generated by Django 4.1.7 on 2023-04-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobScheduledRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='', max_length=200, verbose_name='创建人')),
                ('modifier', models.CharField(default='', max_length=200, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('run_time_at', models.DateTimeField(blank=True, default='1979-01-01 00:00:00', verbose_name='运行时间')),
                ('is_success', models.BooleanField(blank=True, default=False, verbose_name='是否成功')),
                ('system', models.CharField(blank=True, default='', max_length=100, verbose_name='平台')),
                ('node', models.CharField(blank=True, default='', max_length=100, verbose_name='主机节点')),
                ('exc_info', models.CharField(blank=True, default='', max_length=2000, verbose_name='运行异常')),
                ('remark', models.CharField(blank=True, default='', max_length=300, verbose_name='remark')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='Job调度名')),
                ('periodic_task_id', models.IntegerField(blank=True, default=0, verbose_name='定时任务ID')),
            ],
            options={
                'db_table': 'django_celery_jobs_scheduled_log',
                'ordering': ['-id'],
            },
        ),
    ]
