# Generated by Django 4.1.7 on 2023-04-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobperiodicmodel',
            name='crontab',
        ),
    ]
