# Generated by Django 4.1.7 on 2023-04-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('django_celery_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryPeriodicJobModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.periodictask',),
        ),
    ]
