# Generated by Django 4.1.7 on 2023-04-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_jobs', '0002_remove_jobperiodicmodel_crontab'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('mode', models.SmallIntegerField(blank=True, choices=[(1, 'worker'), (2, 'beat'), (3, 'celeryd'), (4, 'multi'), (5, 'init-script'), (6, 'systemd'), (7, 'supervisor')], default=1, verbose_name='Deploy Mode')),
                ('name', models.CharField(blank=True, default='', max_length=30, verbose_name='Name')),
                ('alias', models.CharField(blank=True, default='', max_length=100, verbose_name='Alias')),
                ('value', models.CharField(blank=True, default='', max_length=5000, verbose_name='Value')),
                ('order', models.IntegerField(blank=True, default=1, verbose_name='Order')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Description')),
            ],
            options={
                'db_table': 'django_celery_jobs_deploy_options',
                'ordering': ['order'],
            },
        ),
    ]
