# Generated by Django 4.1.7 on 2023-04-06 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_jobs', '0002_rename_enabled_periodicjobmodel_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicjobmodel',
            name='args',
            field=models.JSONField(blank=True, default=list, verbose_name='Positional Arguments'),
        ),
        migrations.AddField(
            model_name='periodicjobmodel',
            name='deadline_run_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deadline run datetime'),
        ),
        migrations.AddField(
            model_name='periodicjobmodel',
            name='kwargs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Keyword Arguments'),
        ),
        migrations.AddField(
            model_name='periodicjobmodel',
            name='max_run_cnt',
            field=models.IntegerField(blank=True, default=0, verbose_name='Maximum execution times'),
        ),
        migrations.AddField(
            model_name='periodicjobmodel',
            name='priority',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Priority Number between 0 and 255, (priority reversed, 0 is highest)', null=True, validators=[django.core.validators.MaxValueValidator(255)], verbose_name='Priority'),
        ),
    ]
