# Generated by Django 4.1.7 on 2023-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_jobs', '0002_celeryperiodicjobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicjobmodel',
            name='enabled',
            field=models.BooleanField(blank=True, default=False, verbose_name='Start or not'),
        ),
    ]
