# Generated by Django 4.1.7 on 2023-04-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_jobs', '0003_periodicjobmodel_args_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicjobmodel',
            name='title',
            field=models.CharField(default='', max_length=500, unique=True, verbose_name='Task Title'),
        ),
    ]
