# Generated by Django 4.1.7 on 2023-05-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_jobs', '0003_deployoptionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobperiodicmodel',
            name='first_run_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='First run datetime'),
        ),
    ]
