# Generated by Django 4.1.7 on 2023-04-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('django_celery_jobs', '0004_alter_periodicjobmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPeriodicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(default='', max_length=500, unique=True, verbose_name='Task Title')),
                ('is_enabled', models.BooleanField(blank=True, default=False, verbose_name='Start or not')),
                ('max_run_cnt', models.IntegerField(blank=True, default=0, verbose_name='Maximum execution times')),
                ('deadline_run_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deadline run datetime')),
                ('func_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Func Name')),
                ('task_source_code', models.TextField(blank=True, default='', verbose_name='Task Source Code')),
                ('remark', models.CharField(default='', max_length=1000, verbose_name='remark')),
                ('config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config', to='django_celery_jobs.jobconfigmodel')),
                ('crontab', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crontab', to='django_celery_beat.crontabschedule')),
                ('periodic_task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_task', to='django_celery_beat.periodictask')),
            ],
            options={
                'db_table': 'django_celery_jobs_periodic_task',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='periodicjobmodel',
            name='config',
        ),
        migrations.RemoveField(
            model_name='periodicjobmodel',
            name='crontab',
        ),
        migrations.RemoveField(
            model_name='periodicjobmodel',
            name='periodic_task',
        ),
        migrations.DeleteModel(
            name='CeleryJobRunnerResultModel',
        ),
        migrations.DeleteModel(
            name='CeleryPeriodicJobModel',
        ),
        migrations.CreateModel(
            name='BeatPeriodicTaskModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.CreateModel(
            name='CeleryTaskRunnerResultModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_results.taskresult',),
        ),
        migrations.DeleteModel(
            name='PeriodicJobModel',
        ),
    ]
