# Generated by Django 4.1.7 on 2023-05-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_jobs', '0004_jobperiodicmodel_first_run_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryNativeTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(blank=True, default='', max_length=500, verbose_name='Name')),
                ('task', models.CharField(blank=True, db_index=True, default='', max_length=500, verbose_name='Task')),
                ('backend', models.CharField(blank=True, default='', max_length=500, verbose_name='Backend')),
                ('priority', models.IntegerField(blank=True, default=None, null=True, verbose_name='Priority')),
                ('ignore_result', models.BooleanField(blank=True, default=False, verbose_name='Ignore Result')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Hidden')),
                ('desc', models.CharField(blank=True, default='', max_length=500, verbose_name='Desc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
