# Generated by Django 4.1.7 on 2023-05-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_jobs', '0006_alter_celerynativetaskmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobperiodicmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='Task Title'),
        ),
    ]
